### ISSUE TITLE
REST API: Retrigger Existing Repositories

### ISSUE THREAD

**Issue by Sgitario** [quarkus-qe/quarkus-catalog-apps#24]

**Comment by pjgg** [comment]
Proposal
---------------

New Rest API method

> PUT /repository 
> body: NewRepositoryRequest
> response: If repo doesn't exist, then throw an error else return an HTTP 202

**Comment by Sgitario** [comment]
> ## Proposal
> New Rest API method
> 
> > PUT /repository
> > body: NewRepositoryRequest
> > response: If repo doesn't exist, then throw an error else return an HTTP 202

I  think the right endpoint should be: PUT:/repository/{repositoryId}. The body should be UpdateRepositoryRequest only to set the updateable fields (branch and others in the future).
