### ISSUE TITLE
Update GraphQL repositoriesByExtensions and repositories queries to provide totalCount

### ISSUE THREAD

**Issue by rsvoboda** [quarkus-qe/quarkus-catalog-apps#52]
Update GraphQL `repositoriesByExtensions` and `repositories` queries to provide `totalCount`

Inspiration taken from GitHub GraphQL

**Comment by Sgitario** [comment]
Ticket: https://trello.com/c/MkgYaQRz/36-add-totalcount-in-graphql-queries
